language: python
python:
- 3.7.6
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script: nosetests || echo "Tests broken due to lack of CI setup, remedying in future"
